### PR TITLE
Implements MVP

### PR DESCRIPTION
**Pull request by hediet**
This MVP can
* open empty diagrams
* open existing diagrams
* save diagrams
* be used offline

It also includes many lessons learned from the [VS Code extension](https://github.com/hediet/vscode-drawio/).

Technically, compared to your current master, it provides
* a Kotlin rewrite (based on the official extension template)
* a git submodule for the drawio distribution
* a JCEF scheme handler for offline hosting without requiring an http server
* typed messages for bidirectional webview/extension communication
and more.

I guess some meta files need to be tweaked.
Also, I didn't get the *.adoc extension. Since the template is optimized for markdown, I added a readme.md.
The extension.xml description is automatically extracted from the readme.md.

### CODE REVIEW

**Comment by ahus1** [comment]
@hediet - thanks for taking on this task to make this plugin more standard compliant with, and tackling offline functionality.

I gave it a try to run it, and it seems some CSS and JS is missing: The DevTools console of the JCEF preview shows the following messages, and the referenced files are not found within the project. 

Please give it another "push" with these files and I'll have another look.

Cheers!

image

**Comment by ahus1** [comment]
I also pushed some updated logos, plus cleaned up the `.idea` folder. The plugin template doesn't commit any contents in that folder. I chose to commit at least the run configurations. 

When you pull the changes, this will unfortunately remove some local contents from the `.idea` folder previously committed to git. You might need to re-open (or even re-import) the project.

**Comment by hediet** [comment]
Hey ;)

> Please give it another "push" with these files and I'll have another look.

You have to pull the drawio submodule! (`git submodule update --init`)

**Comment by hediet** [comment]
> plus cleaned up the .idea folder

Thanks, I'm quite new to IntelliJ and have no idea what and what not is inside the `.idea` folder. Interesting that the default template I used does not properly setup git ignore (or maybe I didn't copy it over to this branch).

**Comment by ahus1** [comment]
Thanks, that did the trick. Only heard of submodules before, didn't use them before.

Works nicely, I'll merge it!

**Pull request merged**
